/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Random;

public class App {
    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        File file = new File("app\\src\\main\\resources\\recentquotes.json");

        try {
            URL url = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");

            // here i will cast to http connection because it's doing url connection
            HttpURLConnection connection = (HttpURLConnection)url.openConnection();
            connection.setRequestMethod("GET");

            connection.addRequestProperty("User-Agent", "");

            BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));

             String input = reader.readLine();
                 while(input != null){
                     System.out.println(input);
                     input = reader.readLine();
                 }


              reader.close();
             connection.disconnect();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }catch (IOException io){
            System.out.println("Error : "+ io);
        }

    }

    public static String randomBook(Gson gson, File file) throws FileNotFoundException {
            Reader reader = new FileReader(file);
            Book[] books = gson.fromJson( reader, Book[].class);

             Random number = new Random();
             int idx = number.nextInt(books.length);

            String newBook = ""+books[idx];

        return newBook;
    }

 public String getBook(Gson gson, File file,int idx) throws FileNotFoundException {
        Reader reader = new FileReader(file);
        Book[] books = gson.fromJson( reader, Book[].class);

        String newBook = ""+books[idx];

        return newBook;
    }
}

