/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.util.Arrays;
import java.util.Random;


public class App {
    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        File file = new File("app\\src\\main\\resources\\recentquotes.json");

        System.out.println("Should return a random book from file");
        System.out.println(randomBook(gson, file));
    }



    public static String randomBook(Gson gson, File file) throws FileNotFoundException {

            Reader reader = new FileReader(file);
            Book[] books = gson.fromJson( reader, Book[].class);

            Random number = new Random();
            int idx = number.nextInt(books.length);

            String newBook = ""+books[idx];

        return newBook;
    }
}

